name: Validate APKINDEX
description: Verify APKINDEX integrity and package consistency

inputs:
  alpine-version:
    required: true
    description: Alpine version (edge, v3.20, etc.)

runs:
  using: composite
  steps:
    - name: Validate APKINDEX files
      shell: bash
      run: |
        ALPINE_VER="${{ inputs.alpine-version }}"

        echo "=== Validating APKINDEX for Alpine ${ALPINE_VER} ==="

        docker run --rm \
          -v "${{ github.workspace }}/${ALPINE_VER}:/repo:ro" \
          -w /repo \
          alpine:latest sh -c '
            apk add --no-cache apk-tools tar

            ERRORS=0

            for arch in x86_64 aarch64 armv7 armhf; do
              # Check if directory exists and has packages
              if [ ! -d "JamBox/${arch}" ]; then
                continue
              fi

              PKG_COUNT=$(ls -1 JamBox/${arch}/*.apk 2>/dev/null | wc -l)

              if [ $PKG_COUNT -eq 0 ]; then
                echo "Skipping ${arch} (no packages)"
                continue
              fi

              echo "Validating APKINDEX for ${arch} (${PKG_COUNT} packages)..."

              # Check if APKINDEX exists
              if [ ! -f "JamBox/${arch}/APKINDEX.tar.gz" ]; then
                echo "  ✗ ERROR: ${arch} has ${PKG_COUNT} packages but no APKINDEX"
                ERRORS=$((ERRORS + 1))
                continue
              fi

              # Verify tar.gz is valid
              if ! tar -tzf "JamBox/${arch}/APKINDEX.tar.gz" >/dev/null 2>&1; then
                echo "  ✗ ERROR: Invalid APKINDEX.tar.gz for ${arch}"
                ERRORS=$((ERRORS + 1))
                continue
              fi

              # Extract and count entries in APKINDEX
              INDEX_COUNT=$(tar -xzf "JamBox/${arch}/APKINDEX.tar.gz" -O APKINDEX 2>/dev/null | grep -c "^P:" || echo "0")

              echo "  Packages: ${PKG_COUNT}, Indexed: ${INDEX_COUNT}"

              if [ "$PKG_COUNT" -ne "$INDEX_COUNT" ]; then
                echo "  ⚠ WARNING: Package count mismatch for ${arch}"
                # Not a hard error - some packages might be subpackages
              fi

              echo "  ✓ APKINDEX valid for ${arch}"
            done

            if [ $ERRORS -gt 0 ]; then
              echo ""
              echo "✗ Validation failed with ${ERRORS} error(s)"
              exit 1
            fi

            echo ""
            echo "✓ All APKINDEX files validated successfully"
          '
